import Head from 'next/head'
import Message from '../../components/Message'
import About from '../../components/About'
import Skills from '../../components/Skills'
import Projects from '../../components/CardPortfolio'
import Contact from '../../components/Contact'
import Image from "next/image"




export default function Home() {
  return (
    <>
    <div >
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/portfolio.png" />
      </Head>
      <Message heading="Yofran Garnier" message="Full-Stack Web Develop"/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
      </div>
    </>
  )
}
